language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: 1.8.7
    - rvm: jruby-19mode
    - rvm: rbx-19mode
